[workspace]
members = [
    "src/common/base",
    "src/datanode",
    "src/datatypes",
    "src/log-store",
    "src/logical-plans",
    "src/object-store",
    "src/query",
    "src/sql",
    "src/table",
]
